name: "CI Tests"

on:
  push:
    branches:
      - main
      - x64-no-dependencies
    paths:
      - ".github/workflows/rust.yml"
      - "src/**/*.rs"
      - "Cargo.toml"
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: sudo apt install clang lld
      - name: Build
        run: |
          rustc -Copt-level=3 \
                -Ccodegen-units=1 \
                -Clto=fat \
                -Coverflow-checks=false \
                -Cpanic=abort \
                -Csplit-debuginfo=off \
                -Cstrip=symbols \
                -Ctarget-cpu=native \
                -Ccode-model=small \
                -Cdefault-linker-libraries=true \
                ./src/main.rs