name: "CI Tests"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/rust.yml"
      - "src/**/*.rs"
      - "Cargo.toml"
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkouts@v3
      - name: Install Deps
        run: sudo apt install clang lld
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose